#logging:
#  pattern:
#    dateformat: MM-dd HH:mm:ss:SSS
#  level:
#    com.itheima: debug
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    virtual-host: /guest2
    username: guest2
    password: guest2
    connection-timeout: 1s # 设置MQ的连接超时时间
    # 生产者重试机制
    template:
      retry:
        enabled: true # 开启超时重试机制
        initial-interval: 1000ms # 失败后的初始等待时间
        multiplier: 2 # 失败后下次的等待时长倍数，下次等待时长 = initial-interval * multiplier
        max-attempts: 3 # 最大重试次数
    listener:
      simple:
        acknowledge-mode: auto # 抛异常情况重新投递，直到成功为止
        # 消费者重试机制
        retry:
          enabled: true # 开启消费者失败重试
          initial-interval: 1000ms # 初识的失败等待时长为1秒
          multiplier: 1 # 失败的等待时长倍数，下次等待时长 = multiplier * last-interval
          max-attempts: 3 # 最大重试次数
          stateless: true # true无状态；false有状态。如果业务中包含事务，这里改为false
        prefetch: 1 # 能者多劳
    # 生产者确认机制(开了速度会变慢)
    # publisher-confirm-type: correlated # 开启publisher confirm机制，并设置confirm类型
    # publisher-returns: true # 开启publisher return机制（一般不开启，return比较消耗MQ性能）